spring:
    cloud:
        client:
            hostname: localhost
eureka:
    server:
        port: 8761
    instance:
        leaseRenewalIntervalInSeconds: 10
        metadataMap:
            instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.server.port:8761}/eureka/
