eureka:
    server:
        port: 8761
    instance:
        instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
        leaseRenewalIntervalInSeconds: 10
        name: localhost
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.server.port:8761}/eureka/
