eureka:
    server:
        port: 8761
    instance:
        leaseRenewalIntervalInSeconds: 10
    client:
        serviceUrl:
            defaultZone: http://${EUREKA_SERVER_HOSTNAME:localhost}:${eureka.server.port:8761}/eureka/
