eureka:
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.server.port:8761}/eureka/
    server:
    	port: 8761
    instance:
    	name: localhost
