<<<<<<< HEAD
eureka:
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.server.port:8761}/eureka/
    server:
    	port: 8761
    instance:
    	name: localhost
||||||| merged common ancestors
server:
    port: 0
=======
eureka:
    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.server.port:8761}/eureka/
    server:
        port: 8761
    instance:
        name: localhost
>>>>>>> changed eureka config
