spring:
    application:
        name: eureka-server
server:
    port: ${eureka.server.port:8761}

eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
    server:
        waitTimeInMsWhenSyncEmpty: 0
    instance:
        hostname: localhost 
